### ISSUE TITLE
Minimal working Sinatra application not working for me, please help

### ISSUE THREAD

**Issue by Wulfshade** [evilmartians/omniauth-ebay-oauth#5]
Hi,

I set up the required environment variables and run the code but get a message saying "Sinatra doesn’t know this ditty.". It does not recognise the '/auth/ebay' route, not sure if I have to declare that route myself nor what to put in it if I do. I'm new to ruby frameworks so do apologise if this is just something silly and obvious that I'm missing.

require 'sinatra'
require 'omniauth-ebay-oauth'

use Rack::Session::Cookie
use OmniAuth::Builder do
  provider :ebay_oauth, ENV['EBAY_CLIENT_ID'], ENV['EBAY_CLIENT_SECRET'],
    callback_url: ENV['EBAY_RU_NAME'], name: 'ebay'
end

get '/' do
  redirect '/auth/ebay'
end

get '/auth/ebay/callback' do
  "Hello, #{request.env['omniauth.auth'].dig('info', 'name')}"
end

**Comment by Envek** [comment]
It is because of security settings of [OmniAuth 2.x](https://github.com/omniauth/omniauth/releases/tag/v2.0.0).

Add the following line at the top, after `require`s:

```ruby
OmniAuth.config.allowed_request_methods += %i[get]
```

**Comment by Wulfshade** [comment]
Thank you very much for your help and quickness Envek, that is awesome.
