### ISSUE TITLE
No way to test on localhost

### ISSUE THREAD

**Issue by founder3000** [evilmartians/omniauth-ebay-oauth#6]
eBay doesn't let you enter a localhost address as a callback. No way to even develop.  Dead in the water.

**Comment by DmitryTsepelev** [comment]
Unfortuntately yes. You'll have to set up the local certificate and add your localhost to hosts with the domain from the certiifcate. Alternatively, you could try to set up ngrok but it will keep changing the domain on each run.

**Comment by founder3000** [comment]
Thanks for the reply Dmitry! Understood that this is an eBay limitation. Thank you for the excellent gem!

**Comment by founder3000** [comment]
Easier than I thought, we are up and running. Thanks again!
